---
- name: generate serial
  become: false
  shell: bash -c "TZ=UTC date +%s"
  register: serial
  check_mode: no

- name: zone file
  template:
    src: db.j2
    dest: '/etc/bind/zones/db.{{ item.key }}'
    owner: root
    group: root
    mode: 0644
  with_dict: '{{ bind_zones }}'
  register: zone
  notify: bind zone changed
  tags: bind

- name: sign zone file
  shell: 'cd /etc/bind/keys && dnssec-signzone -3 $(head -n 1000 /dev/urandom | sha1sum | cut -b 1-16) -A -N INCREMENT -o {{ item.item.key }} -t /etc/bind/zones/db.{{ item.item.key }}'
  with_items: '{{ zone.results }}'
  when: item.changed and item.item.value.dnssec is defined and item.item.value.dnssec
  notify: bind zone changed
  tags: bind

- name: DNSSEC signing cron job
  template:
    src: dnssec.j2
    dest: /etc/cron.weekly/dnssec
    owner: root
    group: root
    mode: 0700
  tags: bind
